// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwpmbodswholshdocurk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3cG1ib2Rzd2hvbHNoZG9jdXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzYwMDUsImV4cCI6MjA2NDAxMjAwNX0.Bkzglbf11Q5E69Zqz2IYWVM1hBEh51WYYvyKHTN-kE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);